# Generated by Django 5.1.6 on 2025-03-07 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blogpost_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
